version: '3.9'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet62
      POSTGRES_PASSWORD: 26tellaw

    ports:
      - '5432:5432'

    volumes:
      - postgres:/var/lib/postgresql/data



volumes:
  postgres: